from local_ai_assistant_sdk.client import LocalAIAssistantClient
from local_ai_assistant_sdk.exceptions import (
    LocalAIAssistantAPIError,
    LocalAIAssistantConnectionError,
    LocalAIAssistantResponseError,
    LocalAIAssistantSDKError,
)
from local_ai_assistant_sdk.types import (
    ChatMessage,
    ChatResult,
    DeleteResult,
    FileListResult,
    FileRecord,
    HealthStatus,
    KnowledgeBase,
    KnowledgeBaseFile,
    KnowledgeBaseFileListResult,
    KnowledgeBaseListResult,
    Memory,
    MemoryListResult,
    Message,
    MessageListResult,
    ModelInfo,
    ModelsResult,
    RetrievalHit,
    RetrievalResult,
    Session,
    SessionListResult,
)

__version__ = "0.1.0"

__all__ = [
    "LocalAIAssistantClient",
    "LocalAIAssistantSDKError",
    "LocalAIAssistantConnectionError",
    "LocalAIAssistantAPIError",
    "LocalAIAssistantResponseError",
    "HealthStatus",
    "ModelInfo",
    "ModelsResult",
    "Session",
    "SessionListResult",
    "Message",
    "MessageListResult",
    "ChatMessage",
    "ChatResult",
    "DeleteResult",
    "FileRecord",
    "FileListResult",
    "KnowledgeBase",
    "KnowledgeBaseListResult",
    "KnowledgeBaseFile",
    "KnowledgeBaseFileListResult",
    "RetrievalHit",
    "RetrievalResult",
    "Memory",
    "MemoryListResult",
]
